feat: add Jest unit testing library
globaldatanet/amplify-add-fancy pull request #4
Opened 2021-10-05 11:39 UTC by krisraven

Includes:
- add Jest Types
- add Jest config with default values
- add Husky to run pre-push hook
- add test running to npm Scripts

2021-10-05 20:08 UTC, jolo-dev requested changes
Thank you @krisraven ,
Much appreciated.
However, we would like to use [PNPM](https://pnpm.io/). Could you adjust that?

2021-10-05 21:43 UTC, krisraven commented
@jolo-dev sure, I will give it a try.

2021-10-07 01:35 UTC, krisraven commented
Hi @jolo-dev. The `pnpm-lock.yaml` has been updated by running `pnpm install`. Is this what you were asking for in your comment, or are there other things that need to be done?

2021-10-07 05:15 UTC, jolo-dev requested changes
@krisraven Yes, almost.
Please adjust the `package.json` or use my suggestions and delete `package-lock.json`
And then it would be ready to merge.
Thank you 👍

2021-10-07 05:15 UTC, jolo-dev commented on package.json
> +    "coverage": "npm run test -- --coverage --silent",
```suggestion
    "coverage": "pnpm run test -- --coverage --silent",
```

2021-10-07 05:15 UTC, jolo-dev commented on package.json
> +      "pre-push": "npm run test"
```suggestion
      "pre-push": "pnpm run test"
```

2021-10-07 09:57 UTC, krisraven commented on package.json
> +    "coverage": "npm run test -- --coverage --silent",
OK, thank you for confirming.

2021-10-07 11:24 UTC, jolo-dev requested changes
Awesome. We are almost there.
We still don't need the `package-lock.json`. Please delete that.

2021-10-07 11:24 UTC, jolo-dev commented on jest.config.js
> +	testPathIgnorePatterns: ["<rootDir>/node_modules", "<rootDir>/monorepo-lambda"],
We don't need to test the `typescript-lambda` as well.

```suggestion
	testPathIgnorePatterns: ["<rootDir>/node_modules", "<rootDir>/monorepo-lambda", "<rootDir>/typescript-lambda"],
```

2021-10-07 20:13 UTC, merged

2021-10-07 21:47 UTC, krisraven commented
Apologies for the late reply @jolo-dev. Got caught up with attending to some other things. Thanks for fixing and merging. 🏁

2021-10-07 22:02 UTC, jolo-dev commented
All good. You did most of the job. Thank you :)